x-common-config: &common-config
  restart: unless-stopped
  networks:
    - blokmap-dev-network
  env_file:
    - .env

services:
  blokmap-dev-frontend:
    <<: *common-config
    container_name: blokmap-dev-frontend
    build:
      context: ${FRONTEND_DIR}
      dockerfile: Dockerfile.dev
    volumes:
      - ${FRONTEND_DIR}:/blokmap-frontend
    ports:
      - "3000:3000"

  blokmap-dev-backend:
    <<: *common-config
    container_name: blokmap-dev-backend
    build:
      context: ${BACKEND_DIR}
      dockerfile: Dockerfile.dev
    environment:
        - DATABASE_URL=postgresql://blokmap:appel@blokmap-dev-database:5432/blokmap
        - REDIS_URL=redis://blokmap-dev-redis/
        - FRONTEND_URL=http://localhost:3000
    volumes:
      - ${BACKEND_DIR}/src:/volume/blokmap-backend/src
      - ${FILES_LOCATION}:/mnt/files
    ports:
      - "8000:80"
    secrets:
      - cookie-jar-key
    depends_on:
      - blokmap-dev-database
      - blokmap-dev-redis

  blokmap-dev-database:
    <<: *common-config
    image: postgres:17.0-alpine
    container_name: blokmap-dev-database
    environment:
      - PGUSER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=appel
    ports:
      - "6543:5432"

  blokmap-dev-redis:
    <<: *common-config
    image: redis:7-alpine
    container_name: blokmap-dev-redis
    ports:
      - "6379:6379"

  blokmap-dev-nginx:
    image: nginx:alpine
    container_name: blokmap-dev-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - blokmap-dev-frontend
      - blokmap-dev-backend
    networks:
      - blokmap-dev-network

secrets:
  cookie-jar-key:
    file: ./secrets/cookie-jar-key

networks:
  blokmap-dev-network:
    name: blokmap-dev-network
    driver: bridge
