x-common-config: &common-config
  restart: unless-stopped
  networks:
    - blokmap-dev-network
  env_file:
    - .env

services:
  blokmap-dev-frontend:
    <<: *common-config
    container_name: blokmap-dev-frontend
    build:
      context: ${FRONTEND_DIR}
      dockerfile: Dockerfile.dev
    environment:
      - VITE_MAPBOX_API_KEY=${MAPBOX_API_KEY}
    volumes:
      - ${FRONTEND_DIR}:/blokmap-frontend
      - /blokmap-frontend/node_modules
    ports:
      - "3000:3000"

  blokmap-dev-backend:
    <<: *common-config
    container_name: blokmap-dev-backend
    build:
      context: ${BACKEND_DIR}
      dockerfile: Dockerfile.dev
    environment:
        - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@blokmap-dev-database:5432/${DATABASE_NAME}
    volumes:
      - ${BACKEND_DIR}:/blokmap-backend
      - ${FILES_DIR}:/mnt/files
    ports:
      - "8000:80"
    secrets:
      - cookie-jar-key
      - google-oidc-credentials
    depends_on:
      - blokmap-dev-database
      - blokmap-dev-redis

  blokmap-dev-authentication:
    <<: *common-config
    container_name: blokmap-dev-authentication
    build:
      context: ${AUTHENTICATION_DIR}
      dockerfile: Dockerfile.dev
    volumes:
      - ${AUTHENTICATION_DIR}:/auth-server
    ports:
      - "4000:80"
    secrets:
      - cookie-jar-key
      - google-oidc-credentials

  blokmap-dev-database:
    <<: *common-config
    image: postgres:17.0-alpine
    container_name: blokmap-dev-database
    environment:
      - PGUSER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "6543:5432"

  blokmap-dev-redis:
    <<: *common-config
    image: redis:7-alpine
    container_name: blokmap-dev-redis
    ports:
      - "6379:6379"

  blokmap-dev-nginx:
    image: nginx:alpine
    container_name: blokmap-dev-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
      - ${FILES_DIR}:/usr/share/nginx/html/static
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - blokmap-dev-frontend
      - blokmap-dev-backend
      - blokmap-dev-authentication
    networks:
      - blokmap-dev-network

secrets:
  cookie-jar-key:
    file: ./secrets/cookie-jar-key
  google-oidc-credentials:
    file: ./secrets/google-oidc-credentials

networks:
  blokmap-dev-network:
    name: blokmap-dev-network
    driver: bridge
