x-common-config: &common-config
  restart: unless-stopped
  networks:
    - blokmap-dev-network
  env_file:
    - .env

services:
  blokmap-dev-frontend:
    <<: *common-config
    container_name: blokmap-dev-frontend
    build:
      context: ${FRONTEND_DIR}
      dockerfile: Dockerfile.dev
    volumes:
      - ${FRONTEND_DIR}:/blokmap-frontend
    ports:
      - "3000:3000"

  blokmap-dev-backend:
    <<: *common-config
    container_name: blokmap-dev-backend
    build:
      context: ${BACKEND_DIR}
      dockerfile: Dockerfile.dev
    environment:
        - DATABASE_URL=postgresql://blokmap:appel@blokmap-dev-database:5432/blokmap
    volumes:
      - ${BACKEND_DIR}/src:/volume/blokmap-backend/src
    ports:
      - "8000:80"
    depends_on:
      - blokmap-dev-database

  blokmap-dev-database:
    <<: *common-config
    image: postgres:17.0-alpine
    container_name: blokmap-dev-database
    environment:
      - PGUSER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=appel
    ports:
      - "6543:5432"

  blokmap-dev-nginx:
    image: nginx:alpine
    container_name: blokmap-dev-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - blokmap-dev-frontend
      - blokmap-dev-backend
    networks:
      - blokmap-dev-network

networks:
  blokmap-dev-network:
    name: blokmap-dev-network
    driver: bridge
