x-common-config: &common-config
  restart: unless-stopped
  networks:
    - blokmap-network
  env_file:
    - .env

services:
  blokmap-frontend:
    <<: *common-config
    container_name: blokmap-frontend
    build:
      context: ${FRONTEND_DIR}
      dockerfile: Dockerfile.dev
    volumes:
      - ${FRONTEND_DIR}:/blokmap-frontend
    ports:
      - "3000:3000"

  blokmap-backend:
    <<: *common-config
    container_name: blokmap-backend
    build:
      context: ${BACKEND_DIR}
      dockerfile: Dockerfile.dev
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ${BACKEND_DIR}:/blokmap-backend
    ports:
      - "8000:8000"
    depends_on:
      - blokmap-database

  blokmap-database:
    <<: *common-config
    image: postgres:17.0-alpine
    container_name: blokmap-db
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

  blokmap-nginx:
    image: nginx:alpine
    container_name: blokmap-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - blokmap-frontend
      - blokmap-backend
    networks:
      - blokmap-network

networks:
  blokmap-network:
    name: blokmap-network
    driver: bridge