---
- name: Configure bayle
  hosts: bayle
  user: root

  vars_files:
    - vars/authorized_keys.yaml

  roles:
    - role: common

    ###########
    # BLOKMAP #
    ###########

    - role: new_user
      new_user__name: blokmap
      new_user__shell: /bin/zsh
      tags:
        - blokmap
        - user
