---
- name: Configure melina
  hosts: melina
  user: root

  vars_files:
    - vars/authorized_keys.yaml

  roles:
    - role: common

    - role: docker
      tags:
        - docker

    ###########
    # BLOKMAP #
    ###########

    - role: new_user
      new_user__name: blokmap
      new_user__groups: docker
      new_user__shell: /bin/zsh
      new_user__directories:
        - directory: blokmap-staging-data
        - directory: blokmap-staging-authdata
        - directory: blokmap-staging-files
      tags:
        - blokmap
        - user

    - role: nginx_vhost
      nginx_vhost__file: staging.blokmap.ugent.be.conf
      tags:
        - blokmap
        - blokmap-ugent
        - staging
        - nginx

    - role: nginx_vhost
      nginx_vhost__file: staging.blokmap.com.conf
      tags:
        - blokmap
        - blokmap-com
        - staging
        - nginx
