---
- name: Configure pamkolb
  hosts: pamkolb
  user: root

  vars_files:
    - vars/authorized_keys.yaml

  roles:
    - role: common

    ###########
    # BLOKMAP #
    ###########

    - role: new_user
      new_user__name: blokmap
      new_user__shell: /bin/zsh
      new_user__directories:
        - directory: blokmap-data
      tags:
        - blokmap
        - user

    - role: nginx_vhost
      nginx_vhost__file: blokmap.be.conf
      tags:
        - blokmap
        - nginx
