services:
  blokmap-frontend:
    container_name: blokmap-frontend
    build:
      context: ${FRONTEND_DIR}
      dockerfile: Dockerfile.prod
    volumes:
      - ${FRONTEND_DIR}:/blokmap-frontend
    profiles:
      - production

  blokmap-backend:
    image: ghcr.io/blokmap/backend:latest
    container_name: blokmap-backend-prod
    environment:
      - DATABASE_NAME=blokmap
      - DATABASE_USER=blokmap
    secrets:
      - db-password
    depends_on:
      - blokmap-db
    ports:
      - "3000:80"

  blokmap-db:
    image: postgres:17.0-alpine
    container_name: blokmap-db
    environment:
      - POSTGRES_DB=blokmap
      - POSTGRES_USER=blokmap
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - "5432"
    volumes:
      - type: bind
        source: ~/blokmap-data
        target: /var/lib/postgresql/data
    secrets:
      - db-password
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

secrets:
  db-password:
    file: ./secrets/db-password.txt
