x-common-config: &common-config
    restart: unless-stopped
    env_file: .env
    networks:
        - blokmap-prod-network

services:
    blokmap-prod-frontend:
        image: ghcr.io/blokmap/blokmap-frontend:latest
        container_name: blokmap-prod-frontend
        <<: *common-config
        restart: "no"
        volumes:
          - ${FRONTEND_PROD_DIR}:/blokmap-frontend/public

    blokmap-prod-backend:
        image: ghcr.io/blokmap/blokmap-backend:latest
        container_name: blokmap-prod-backend
        <<: *common-config
        environment:
          - DATABASE_URL=postgresql://blokmap:appel@blokmap-prod-database:5432/blokmap
          - REDIS_URL=redis://blokmap-prod-redis/
          - FRONTEND_URL=https://blokmap.ebosprojects.be
        ports:
          - "3000:80"
        secrets:
          - cookie-jar-key
        depends_on:
          - blokmap-prod-database
          - blokmap-prod-redis

    blokmap-prod-database:
        image: postgres:17.0-alpine
        container_name: blokmap-prod-database
        <<: *common-config
        environment:
          - PGUSER=blokmap
          - POSTGRES_USER=blokmap
          - POSTGRES_PASSWORD=appel
          - POSTGRES_DB=blokmap
        expose:
            - "5432"
        volumes:
          - type: bind
            source: ~/blokmap-data
            target: /var/lib/postgresql/data
        healthcheck:
            test: [ "CMD", "pg_isready" ]
            interval: 30s
            timeout: 5s
            retries: 5
            start_period: 30s

    blokmap-prod-redis:
        image: redis:7-alpine
        container_name: blokmap-prod-redis
        <<: *common-config
        ports:
          - "6379:6379"

secrets:
    cookie-jar-key:
        file: ./secrets/cookie-jar-key

networks:
    blokmap-prod-network:
        name: blokmap-prod-network
        driver: bridge
