x-common-config: &common-config
    restart: unless-stopped
    env_file: .env
    networks:
        - blokmap-prod-network

services:
    blokmap-prod-frontend:
        image: ghcr.io/blokmap/blokmap-prod-frontend:latest
        container_name: blokmap-prod-frontend
        <<: *common-config
        restart: "no"
        environment:
          - VITE_MAPBOX_API_KEY=${MAPBOX_API_KEY}
        volumes:
          - ${FRONTEND_PROD_DIR}:/blokmap-frontend/public

    blokmap-prod-docs:
        image: ghcr.io/blokmap/blokmap-docs:latest
        container_name: blokmap-prod-docs
        <<: *common-config
        restart: "no"
        volumes:
          - ${DOCS_PROD_DIR}:/blokmap-docs/docs/.vitepress/dist

    blokmap-prod-backend:
        image: ghcr.io/blokmap/blokmap-prod-backend:latest
        container_name: blokmap-prod-backend
        <<: *common-config
        environment:
          - DATABASE_URL=postgresql://blokmap:appel@blokmap-prod-database:5432/blokmap
          - REDIS_URL=redis://blokmap-prod-redis/
          - PRODUCTION=true
          - SKIP_VERIFY=false
          - BACKEND_URL=https://blokmap.ugent.be/api/
          - FRONTEND_URL=https://blokmap.ugent.be/
          - STATIC_URL=https://blokmap.ugent.be/static/
        volumes:
          - type: bind
            source: /srv/static
            target: /mnt/files
        ports:
          - "3000:80"
        secrets:
          - cookie-jar-key
          - claims-cookie-key
          - google-oidc-credentials
        depends_on:
          - blokmap-prod-database
          - blokmap-prod-redis

    blokmap-prod-migrations:
        image: ghcr.io/blokmap/blokmap-prod-migrations:latest
        container_name: blokmap-prod-migrations
        <<: *common-config
        restart: "no"
        environment:
          - DATABASE_URL=postgresql://blokmap:appel@blokmap-prod-database:5432/blokmap
        volumes:
          - type: bind
            source: ~/blokmap-files
            target: /mnt/files
        depends_on:
          - blokmap-prod-database

    blokmap-staging-authentication:
        image: ghcr.io/blokmap/blokmap-prod-authentication:latest
        container_name: blokmap-prod-authentication
        <<: *common-config
        environment:
          - FRONTEND_URL=https://blokmap.ugent.be/
          - AUTHENTICATION_URL=https://blokmap.ugent.be/api/auth/
        ports:
          - "3003:80"
        secrets:
          - cookie-jar-key
          - claims-cookie-key
          - google-oidc-credentials

    blokmap-prod-database:
        image: postgres:17.0-alpine
        container_name: blokmap-prod-database
        <<: *common-config
        environment:
          - PGUSER=blokmap
          - POSTGRES_USER=blokmap
          - POSTGRES_PASSWORD=appel
          - POSTGRES_DB=blokmap
        ports:
            - "5432:5432"
        volumes:
          - type: bind
            source: ~/blokmap-data
            target: /var/lib/postgresql/data
        healthcheck:
            test: [ "CMD", "pg_isready" ]
            interval: 30s
            timeout: 5s
            retries: 5
            start_period: 30s

    blokmap-prod-redis:
        image: redis:7-alpine
        container_name: blokmap-prod-redis
        <<: *common-config
        ports:
          - "6379:6379"

secrets:
    cookie-jar-key:
        file: ./secrets/cookie-jar-key
    claims-cookie-key:
        file: ./secrets/claims-cookie-key
    google-oidc-credentials:
        file: ./secrets/google-oidc-credentials

networks:
    blokmap-prod-network:
        name: blokmap-prod-network
        driver: bridge
