x-common-config: &common-config
    restart: unless-stopped
    env_file: .env
    networks:
        - blokmap-staging-network

services:
    blokmap-staging-frontend:
        image: ghcr.io/blokmap/blokmap-staging-frontend:latest
        container_name: blokmap-staging-frontend
        <<: *common-config
        restart: "no"
        environment:
          - VITE_MAPBOX_API_KEY=${MAPBOX_API_KEY}
        volumes:
          - ${FRONTEND_STAGING_DIR}:/blokmap-frontend/public

    blokmap-staging-backend:
        image: ghcr.io/blokmap/blokmap-staging-backend:latest
        container_name: blokmap-staging-backend
        <<: *common-config
        environment:
          - DATABASE_URL=postgresql://blokmap:appel@blokmap-staging-backend-database:5432/blokmap
          - REDIS_URL=redis://blokmap-staging-redis/
          - BACKEND_URL=https://staging.blokmap.ugent.be/api/
          - FRONTEND_URL=https://staging.blokmap.ugent.be/
          - STATIC_URL=https://staging.blokmap.ugent.be/static/
        volumes:
          - type: bind
            source: /srv/static
            target: /mnt/files
        ports:
          - "3001:80"
        secrets:
          - cookie-jar-key
          - claims-cookie-key
          - google-oidc-credentials
        depends_on:
          - blokmap-staging-backend-database
          - blokmap-staging-redis

    blokmap-staging-migrations:
        image: ghcr.io/blokmap/blokmap-staging-migrations:latest
        container_name: blokmap-staging-migrations
        <<: *common-config
        restart: "no"
        environment:
          - DATABASE_URL=postgresql://blokmap:appel@blokmap-staging-backend-database:5432/blokmap
        volumes:
          - type: bind
            source: ~/blokmap-staging-files
            target: /mnt/files
        depends_on:
          - blokmap-staging-backend-database

    blokmap-staging-authentication:
        image: ghcr.io/blokmap/blokmap-staging-authentication:latest
        container_name: blokmap-staging-authentication
        <<: *common-config
        environment:
          - FRONTEND_URL=https://staging.blokmap.ugent.be/
          - AUTHENTICATION_URL=https://staging.blokmap.ugent.be/api/auth/
          - DATABASE_URL=postgresql://blokmap:appel@blokmap-staging-authentication-database:5432/blokmap_authentication
        ports:
          - "3002:80"
        secrets:
          - cookie-jar-key
          - claims-cookie-key
          - google-oidc-credentials
        depends_on:
          - blokmap-staging-authentication-database

    blokmap-staging-backend-database:
        image: postgres:17.0-alpine
        container_name: blokmap-staging-backend-database
        <<: *common-config
        environment:
          - PGUSER=blokmap
          - POSTGRES_USER=blokmap
          - POSTGRES_PASSWORD=appel
          - POSTGRES_DB=blokmap
        ports:
          - "6543:5432"
        volumes:
          - type: bind
            source: ~/blokmap-staging-data
            target: /var/lib/postgresql/data
        healthcheck:
            test: [ "CMD", "pg_isready" ]
            interval: 30s
            timeout: 5s
            retries: 5
            start_period: 30s

    blokmap-staging-authentication-database:
        image: postgres:17.0-alpine
        container_name: blokmap-staging-authentication-database
        <<: *common-config
        environment:
          - PGUSER=blokmap
          - POSTGRES_USER=blokmap
          - POSTGRES_PASSWORD=appel
          - POSTGRES_DB=blokmap_authentication
        ports:
          - "7654:5432"
        volumes:
          - type: bind
            source: ~/blokmap-staging-authdata
            target: /var/lib/postgresql/data
        healthcheck:
            test: [ "CMD", "pg_isready" ]
            interval: 30s
            timeout: 5s
            retries: 5
            start_period: 30s

    blokmap-staging-redis:
        image: redis:7-alpine
        container_name: blokmap-staging-redis
        <<: *common-config
        ports:
          - "6379:6379"

secrets:
    cookie-jar-key:
        file: ./secrets/cookie-jar-key
    claims-cookie-key:
        file: ./secrets/claims-cookie-key
    google-oidc-credentials:
        file: ./secrets/google-oidc-credentials

networks:
    blokmap-staging-network:
        name: blokmap-staging-network
        driver: bridge
