---
- name: Configure pamkolb
  hosts: pamkolb
  user: root

  vars_files:
    - vars/authorized_keys.yaml

  roles:
    - role: common

    ###########
    # BLOKMAP #
    ###########

    - role: new_user
      new_user__name: blokmap
      tags:
        - blokmap
        - user
      new_user__directories: blokmap-data

    - role: nginx_vhost
      nginx_vhost__file: blokmap.be
      tags:
        - blokmap
        - nginx
