---
- name: Simple test playbook
  hosts: test
  gather_facts: false

  vars_files:
    - vars/authorized_keys.yaml

  roles:
    - role: common

    ###########
    # BLOKMAP #
    ###########

    - role: new_user
      new_user__name: blokmap

    - role: nginx_vhost
      nginx_vhost__file: blokmap.be
