---
- name: Simple test playbook
  hosts: test
  gather_facts: false

  vars_files:
    - vars/authorized_keys.yaml

  pre_tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update-cache: true

  roles:
    - role: root_ssh_keys

    ###########
    # BLOKMAP #
    ###########

    - role: new_user
      new_user__name: blokmap

    - role: nginx_vhost
      nginx_vhost__file: blokmap.be
