name: Deploy to Staging

permissions:
    packages: read

on:
    workflow_dispatch:

concurrency:
  group: deploy-staging
  cancel-in-progress: true

jobs:
    deploy:
        runs-on: self-hosted
        steps:
          - name: Run migrations
            uses: appleboy/ssh-action@v1.2.1
            with:
                host: ${{ secrets.STAGING_HOST }}
                username: ${{ secrets.STAGING_USERNAME }}
                key: ${{ secrets.PRODUCTION_SSH_KEY }}
                debug: true
                script: |
                    cd /home/blokmap/deploy && git pull
                    docker compose -f /home/blokmap/deploy/production/compose.staging.yaml pull
                    docker compose -f /home/blokmap/deploy/production/compose.staging.yaml up blokmap-staging-migrations

          - name: Deploy front and backend
            uses: appleboy/ssh-action@v1.2.1
            with:
                host: ${{ secrets.STAGING_HOST }}
                username: ${{ secrets.STAGING_USERNAME }}
                key: ${{ secrets.PRODUCTION_SSH_KEY }}
                debug: true
                script: |
                    cd /home/blokmap/deploy && git pull
                    docker compose -f /home/blokmap/deploy/production/compose.staging.yaml pull
                    docker compose -f /home/blokmap/deploy/production/compose.staging.yaml up blokmap-staging-frontend blokmap-staging-backend -d
