---
- name: Create new user
  ansible.builtin.user:
    name: "{{ new_user__name }}"
    shell: "{{ new_user__shell }}"
    append: true
    groups: "{{ new_user__groups }}"
  register: user

- name: Copy Oh My Zsh setup
  ansible.builtin.copy:
    src: /root/.oh-my-zsh/
    dest: "{{ user.home }}/.oh-my-zsh/"
    remote_src: true
    mode: "755"
    directory_mode: "755"
    group: "{{ user.group }}"
    owner: "{{ user.name }}"
  when: user.shell == "/bin/zsh"

- name: Copy zshrc
  ansible.builtin.copy:
    src: /root/.zshrc
    dest: "{{ user.home }}/.zshrc"
    remote_src: true
    mode: "644"
    group: "{{ user.group }}"
    owner: "{{ user.name }}"
  when: user.shell == "/bin/zsh"

- name: Copy p10k.zsh
  ansible.builtin.copy:
    src: /root/.p10k.zsh
    dest: "{{ user.home }}/.p10k.zsh"
    remote_src: true
    mode: "644"
    group: "{{ user.group }}"
    owner: "{{ user.name }}"
  when: user.shell == "/bin/zsh"

- name: Create user directies
  ansible.builtin.file:
    path: "{{ user.home }}/{{ item.directory }}"
    mode: "{{ item.mode | default('0755') }}"
    owner: "{{ item.owner | default(user.name) }}"
    group: "{{ item.group | default(user.name) }}"
    state: directory
  with_items: "{{ new_user__directories }}"

- name: Install authorized keys
  ansible.posix.authorized_key:
    user: "{{ user.name }}"
    key: "{{ new_user__authorized_keys }}"
    exclusive: false
